pr: none
trigger: none

# Customize build number to include major version
# Example: v9_20201022.1
name: 'tensile_perf_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - group: 'Github and NPM secrets'
  - group: 'Tensile Perf Auth Tokens'

jobs:
  - template: .devops/templates/compliance-job.yml

  - job: Release
    dependsOn: Compliance
    pool: '1ES-Host-Ubuntu'
    workspace:
      clean: all
    steps:
      # For multiline scripts, we want the whole task to fail if any line of the script fails.
      # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
      # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
      # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
      # errexit:errtrace for better error behavior.
      - script: |
          echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
        displayName: Force exit on error (bash)

      - task: NodeTool@0
        inputs:
          versionSpec: '18.16.0'
          checkLatest: false
        displayName: 'Install Node.js'

      - script: |
          git config user.name "Fluent UI Build"
          git config user.email "fluentui-internal@service.microsoft.com"
          git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/fluentui.git
        displayName: Authenticate git for pushes

      - script: |
          yarn install --frozen-lockfile --ignore-engines
        displayName: Install dependencies

      - script: |
          yarn nx run-many --target=lint --all --verbose --skip-nx-cache --exclude mail-ui
        displayName: yarn lint

      - script: |
          yarn nx run-many --target=type-check --all --verbose --skip-nx-cache --exclude mail-ui
        displayName: yarn type-check

      - script: |
          yarn build --skip-nx-cache
        displayName: yarn build

      # - script: |
      #     yarn nx run-many --target=test --all --verbose --exclude mail-ui --skip-nx-cache
      #   displayName: yarn test

      # - script: |
      #     yarn publish:beachball --token $(NPM_TOKEN_TENSILE_PERF)
      #     git reset --hard origin/main
      #   env:
      #     GITHUB_PAT: $(githubPAT)
      #   displayName: Publish changes and bump versions

      # - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
      #   displayName: 📒 Generate Manifest
      #   inputs:
      #     BuildDropPath: $(System.DefaultWorkingDirectory)

      # - task: PublishPipelineArtifact@1
      #   displayName: 📒 Publish Manifest
      #   inputs:
      #     artifactName: SBom-$(System.JobAttempt)
      #     targetPath: $(System.DefaultWorkingDirectory)/_manifest

      # This would usually be run automatically (via a pipeline decorator from an extension), but the
      # thorough cleanup step prevents it from working. So run it manually here.
      # - task: ComponentGovernanceComponentDetection@0
      #   displayName: 'Component governance detection'
      #   inputs:
      #     sourceScanPath: $(Agent.BuildDirectory)
      #   condition: succeeded()
      #   timeoutInMinutes: 5
      #   continueOnError: true

      # - template: .devops/templates/cleanup.yml
      #   parameters:
      #     checkForModifiedFiles: false
