name: CI

on:
  push:
    branches:
      - main
      - website

permissions:
  contents: 'read'
  actions: 'read'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'

      - name: swap npmrc
        run: |
          mv .npmrc backup.npmrc
          mv ci.npmrc .npmrc

      - name: Install dependencies
        env:
          AZURE_DEVOPS_PASSWORD: ${{secrets.AZURE_DEVOPS_PASSWORD}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: bash ${GITHUB_WORKSPACE}/yarn-ci.sh

      - name: restore npmrc
        run: |
          mv .npmrc ci.npmrc
          mv backup.npmrc .npmrc

      - run: yarn nx run-many --target=lint --all
      - run: yarn nx run-many --target=type-check --all
      - run: yarn nx run-many --target=generate-api --configuration=ci --all
      - run: yarn nx run-many --target=build --all
      - run: yarn nx run-many --target=test --all

  E2E:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'

      - name: swap npmrc
        run: |
          mv .npmrc backup.npmrc
          mv ci.npmrc .npmrc

      - name: Install dependencies
        env:
          AZURE_DEVOPS_PASSWORD: ${{secrets.AZURE_DEVOPS_PASSWORD}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: bash ${GITHUB_WORKSPACE}/yarn-ci.sh

      - name: restore npmrc
        run: |
          mv .npmrc ci.npmrc
          mv backup.npmrc .npmrc

      # - name: Install browsers
      #   run: npx playwright install

      # - name: Run E2E Tests
      #   run: yarn nx run-many --target=e2e --all